-- Create social_links
CREATE TABLE IF NOT EXISTS social_links (
  id CHAR(36) NOT NULL PRIMARY KEY,
  name TEXT NOT NULL,
  platform VARCHAR(64) NOT NULL,
  url TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Create flowers
CREATE TABLE IF NOT EXISTS flowers (
  id CHAR(36) NOT NULL PRIMARY KEY,
  name TEXT NOT NULL,
  type VARCHAR(255),
  description TEXT,
  price DECIMAL(12,2) DEFAULT 0,
  stock INT DEFAULT 0,
  image_url TEXT,
  is_available TINYINT(1) DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
